# Generated by Django 2.0.2 on 2018-03-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_text', models.CharField(max_length=500)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootcause', to='excuses.Bug')),
            ],
        ),
        migrations.AddField(
            model_name='actionplan',
            name='rootcause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionplan', to='excuses.RootCause'),
        ),
    ]
